title: Carson Uecker-Herman # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description:  # your text below (remove <br> elements if you don't need line breaks)
  Computer Science Undergraduate 
  Grand Valley State University
  <a href="www.linkedin.com/in/carsonuh">View My LinkedIn Profile</a> 
